=== StepanovSergey/Task3/src/products.dtd
<!ELEMENT products (product+)>
<!ELEMENT product (producer,model,date-of-issue,color,(not-in-stock|price))>
<!ELEMENT producer (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT date-of-issue (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT not-in-stock EMPTY>

=== StepanovSergey/Task3/src/products.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE products SYSTEM "products.dtd"> -->
<products xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.epam.com" xs:schemaLocation="http://www.epam.com products.xsd">
	<product>
		<producer>Samsung</producer>
		<model>GS003</model>
		<date-of-issue>02-09-2012</date-of-issue>
		<color>White</color>
		<price>600</price>
	</product>
	<product>
		<producer>Apple</producer>
		<model>IP005</model>
		<date-of-issue>05-12-2012</date-of-issue>
		<color>Black</color>
		<not-in-stock />
	</product>
	<product>
		<producer>Nokia</producer>
		<model>WP920</model>
		<date-of-issue>20-10-2012</date-of-issue>
		<color>Red</color>
		<price>900</price>
	</product>
	<product>
		<producer>Huawei</producer>
		<model>HU886</model>
		<date-of-issue>20-05-2012</date-of-issue>
		<color>White</color>
		<not-in-stock />
	</product>
	<product>
		<producer>Samsung</producer>
		<model>GT007</model>
		<date-of-issue>15-08-2012</date-of-issue>
		<color>Silver</color>
		<price>400</price>
	</product>
</products>
